### ISSUE TITLE
list-all ansible-base contains invalid output

### ISSUE THREAD

**Issue by mcbloch** [amrox/asdf-pyapp#16]
**Describe the bug**

Running `asdf list-all ansible-base` returns version numbers surrounded by invalid output.

The output I got was 
```
➜ asdf list-all ansible-base
-atplotlib
-atplotlib
(/home/me/.local/lib/python3.9/site-packages)
(/home/me/.local/lib/python3.9/site-packages
0.0.1a1
0.0.1a2
2.10.0
2.10.0b1
2.10.0rc1
2.10.0rc2
2.10.0rc3
2.10.0rc4
2.10.1
2.10.1rc1
2.10.1rc2
2.10.1rc3
2.10.2
2.10.2rc1
2.10.3
2.10.3rc1
2.10.4
2.10.4rc1
2.10.5
2.10.5rc1
2.10.6
2.10.6rc1
2.10.7
2.10.7rc1
2.10.8
2.10.8rc1
2.10.9
2.10.9rc1
2.10.10
2.10.10rc1
2.10.11
2.10.11rc1
2.10.12
2.10.12rc1
2.10.13
2.10.13rc1
2.10.14
2.10.14rc1
2.10.15
2.10.15rc1
2.10.16)
2.10.16rc1
ERROR:
Ignoring
Ignoring
No
WARNING:
WARNING:
ansible-base==
distribution
distribution
distribution
for
found
invalid
invalid
matching
```

**Steps to reproduce**

    asdf plugin add ansible-base https://github.com/amrox/asdf-pyapp.git
    asdf list-all ansible-base

**Expected behavior**

I expected to get a valid list of installable ansible versions.

**Edit**
`asdf install ansible-base latest` is also broken as it tries to install `ansible-base==2.10.16)`

**Comment by amrox** [comment]
sorry about the bug

I haven't been able to reproduce it, so I'm guessing you have different system python3 / pip versions.

Can you run?

```
python3 -m pip --version
```

**Comment by mcbloch** [comment]
> sorry about the bug
> 
> I haven't been able to reproduce it, so I'm guessing you have different system python3 / pip versions.
> 
> Can you run?
> 
> ```
> python3 -m pip --version
> ```

I very much can :)
```
pip 21.2.4 from /home/me/.asdf/installs/python/3.10.1/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by amrox** [comment]
@mcbloch ok I still wasn't able to reproduce, so I'm going to need some more information. I just pushed a change that should provide a debug log.

Can you please do the following?

1. `asdf plugin update ansible-base`
2. set `ASDF_PYAPP_DEBUG=1` in your shell
3. `asdf list-all ansible-base`
4. share your `/tmp/asdf-pyapp-debug.log`

**Comment by mcbloch** [comment]
> @mcbloch ok I still wasn't able to reproduce, so I'm going to need some more information. I just pushed a change that should provide a debug log.
> 
> Can you please do the following?
> 
>     1. `asdf plugin update ansible-base`
> 
>     2. set `ASDF_PYAPP_DEBUG=1` in your shell
> 
>     3. `asdf list-all ansible-base`
> 
>     4. share your `/tmp/asdf-pyapp-debug.log`

I put it in a pastebin because it's a long log file. I can paste the content in GitHub if you'd rather have that.
https://pastebin.com/n0hX8EQj

**Comment by amrox** [comment]
@mcbloch thank you for your patience. I'm getting a 404 on that link unfortunately :( Maybe try to re-post? Or a [gist](https://gist.github.com)?

**Comment by amrox** [comment]
hi @mcbloch - just checking in, since it's been about 30 days since your last response
